basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.course_all, name='store_home'),
    path('', views.course_all, name='course_all'),
    path('<slug:slug>', views.course_detail, name='course_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

tutorWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
]
# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class CourseManager(models.Manager):
    def get_queryset(self):
        return super(CourseManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Course(models.Model):
    category = models.ForeignKey(Category, related_name='course', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='course_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.BigIntegerField()
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    courses = CourseManager()

    class Meta:
        verbose_name_plural = 'courses'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:course_detail', args=[self.slug])

    def __str__(self):
        return self.title

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Course


def course_all(request):
    courses = Course.courses.all()
    return render(request, 'store/index.html', {'courses': courses})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    courses = Course.objects.filter(category=category)
    return render(request, 'store/category.html', {'category': category, 'courses': courses})


def course_detail(request, slug):
    course = get_object_or_404(Course, slug=slug, in_stock=True)
    return render(request, 'store/single.html', {'course': course})

templates/store/category.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Courses{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for course in courses %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ course.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ course.get_absolute_url }}">{{ course.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">zzz</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/store/index.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}E-Learning{% endblock %}
{% block content %}


<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-3">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold">welcome to tutor app</h1>
        <p class="lead text-muted">lorem ipsum vv may may.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Make an account</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">All Courses</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for course in courses %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ course.image.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ course.get_absolute_url }}">{{ course.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">zzz</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/store/single.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block title %}
{{ course.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ course.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ course.title }}</h1>
                <p><span class="lead">{{ course.author }}</span> (Author)</p>
                <p>{{ course.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Online</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold"> {{ course.price|intcomma }} VND</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <button type="button" id="add-button" value="{{course.id}}" class="btn btn-secondary btn-sm">Add to basket</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>


<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                courseid: $('#add-button').val(),
                courseqty: 1,
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}